### ISSUE TITLE
Make available on Confluent Hub

### ISSUE THREAD

**Issue by rmoff** [RedHatInsights/expandjsonsmt#11]
Hi, 
This SMT looks really useful. Have you considered making it available through Confluent Hub? That way users can install it with a single command instead of having to build it themselves. Details of how to submit are [here](https://docs.confluent.io/home/connect/confluent-hub/contributing.html). Thanks!

**Comment by Josca** [comment]
We have no plans to do that yet. Can you or anyone from Confluent help with that?

**Comment by rmoff** [comment]
I will create a [package](https://docs.confluent.io/home/connect/confluent-hub/component-archive.html#confluent-hub-component-archive) manually and work with my colleagues to get it submitted to Confluent Hub.

For future releases I think this can be automated -- there's a maven plugin here: https://docs.confluent.io/platform/current/connect/kafka-connect-maven-plugin/kafka-connect-mojo.html

**Comment by rmoff** [comment]
Now listed at https://www.confluent.io/hub/redhatinsights/expandjsonsmt
